blank_issues_enabled: false
contact_links:
  - name: Discussions from MK repository
    url: https://github.com/wulfland/AccelerateDevOps/disscussions/new
    about: Please use this link to start a new discussion for issues that are not bug, or feature request